name: Ensure no changes to tracked files
description: Detect any changes to tracked files and fail the forkflow.
inputs:
  post-pr-comment:
    description: Post a comment with changes (only on pull requests)
    required: false
    default: true
  comment-header:
    description: Header for the PR comment
    required: false
    default: "Tracked files have changed:"
  comment-footer:
    description: Footer for the PR comment
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: git diff
      id: git-diff
      uses: mathiasvr/command-output@v2.0.0
      with:
        shell: bash
        run: git diff --diff-algorithm=histogram --exit-code

    - name: Post PR comment
      if: >-
        failure() &&
        github.event_name == 'pull_request' &&
        inputs.post-pr-comment == 'true'
      uses: thollander/actions-comment-pull-request@v3
      with:
        comment-tag: ${{ github.job }}
        mode: recreate
        message: |
          ${{ inputs.comment-header }}
          ```diff
          ${{ steps.git-diff.outputs.stdout }}```
          ${{ inputs.comment-footer }}
