name: Build package wheels

on: [workflow_dispatch]

jobs:
  # build-windows:
  #   name: Windows
  #   runs-on: windows-latest
  #   # strategy:
  #   #   matrix:
  #   #     os: [ubuntu-latest, windows-latest, macos-13, macos-14]

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         arch: x64

  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.12"
  #     - name: Install cibuildwheel
  #       run: pip install cibuildwheel==2.17.0

  #     - name: Build wheels
  #       run: python -m cibuildwheel --output-dir wheelhouse
  #       env:
  #         CIBW_SKIP: *-win32
  #         CMAKE_GENERATOR: Ninja
  #         CIBW_BUILD_VERBOSITY: 1

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: wheels-windows
  #         path: ./wheelhouse/*.whl

  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.17.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CMAKE_GENERATOR: Ninja
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          path: ./wheelhouse/*.whl
