name: Publish Docs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install zint
        run: pip install .[docs]

      - name: Build docs
        run: sphinx-build docs build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
